#!/bin/sh

mkdir -p /opt/paperless/consume
mkdir -p /opt/paperless/media

python3.9 -m venv --system-site-packages venv
. venv/bin/activate

pip install --upgrade pip
pip install -r requirements.txt

cd src
python3 manage.py migrate
DJANGO_SUPERUSER_PASSWORD="admin" python3 manage.py createsuperuser --noinput --email=root@localhost --username=admin
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "/opt/paperless/data/nltk" snowball_data
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "/opt/paperless/data/nltk" stopwords
python3 -W ignore::RuntimeWarning -m nltk.downloader -d "/opt/paperless/data/nltk" punkt

# Fix for server Websockets (see https://github.com/paperless-ngx/paperless-ngx/issues/6349)
patch -R src/paperless/settings.py < /tmp/paperless_daphne.patch

deactivate
