#!/bin/sh

# PROVIDE: paperlesstaskqueue
# REQUIRE: DAEMON redis
# KEYWORD: shutdown

. /etc/rc.subr


name="paperlesstaskqueue"
rcvar="${name}_enable"
procname="daemon"

pidfile="/var/run/${name}.pid"


command="/usr/sbin/daemon"
command_args="-f -P ${pidfile} -u paperless /usr/local/sbin/${name}"


load_rc_config $name
run_rc_command "$1"
